export const PRODUCT_REQUEST = "PRODUCT_REQUEST";

export const PRODUCT_FAILURE = "PRODUCT_FAILURE"; 
//post
export const ADD_PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
//get
export const GET_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
 
